### ISSUE TITLE
Support for operators ro enhance pre conditions

### ISSUE THREAD

**Issue by ghansham** [dagu-org/dagu#1016]
Right now pre conditions provide use of commands, variables but not operators like and, or, not, contains operators. We propose enhancement for preconditions to include above.

This has been discussed by @yottahmd in detail:

https://github.com/dagu-org/dagu/issues/598

@kriyanshii has worked in this direction quite a bit.

**Comment by yohamta0** [comment]
One possible Idea:
```yaml
preconditions:
    and:
      - or:
        - condition: "test -f /tmp/flag1" # cond 1
        - condition: "test -f /tmp/flag2" # cond 2
      - condition: "test -f /tmp/flag3" # cond 3
      - condition: "test -f /tmp/flag4" # cond 4
```
This translates to the internal representation: `(AND (OR cond1, cond2), cond3, cond4))`.
I'm wondering how other workflow software handles complex conditions like this.

**Comment by ghansham** [comment]
We may need some parser in go that parse statements like:

($var1 == 1 || $var1 == 3) && $var2 == 4

and help in evaluating conditions.

We can think about going in baby steps by keeping depth of conditions to 1 level and add basic operator support like and, or and ismember, isnotmember. 

@kriyanshii did some work using LISP expression evaluation for the expression mentioned by you:

(AND (OR cond1, cond2), cond3, cond4))

to implement complex pre conditions.
User may have to input the condition in above form.


Check this:
https://pkg.go.dev/github.com/PaesslerAG/gval

This provides expression evaluation in golang

**Comment by yohamta0** [comment]
I’ve put together a draft design for this feature. It’s straightforward and covers most use cases. If we ever need more complex, nested conditions, we can add them later. @ghansham, I’d love to hear your thoughts :)

**Changes**
Add an optional `operator` field that supports "or" logic at the top level:

```yaml
# Current behavior (implicit AND - unchanged)
preconditions:
  - condition: "${A}"
    expected: "1"
  - condition: "${B}"
    expected: "2"

# New: OR operator
preconditions:
  operator: or
  conditions:
    - condition: "${STATUS}"
      expected: "ready"
    - condition: "test -f /tmp/override.flag"
```

**Examples**
Run on weekdays OR with override:
```yaml
steps:
  - name: daily-job
    command: ./process.sh
    preconditions:
      operator: or
      conditions:
        - condition: "`date +%u`"
          expected: "re:[1-5]"  # Mon-Fri
        - condition: "test -f /tmp/weekend-override"
```

Repeat while multiple states:
```yaml
repeatPolicy:
  operator: or
  conditions:
    - condition: "${STATUS}"
      expected: "STARTING"
    - condition: "${STATUS}"
      expected: "PENDING"
  intervalSec: 30
```

**Comment by ghansham** [comment]
Thanks for giving the details. May be in the elementary condition also we can support optional operators like eq, ne, in, notin (default case being eq)
E.g.
```yaml
- condition: "${STATUS}"
  operator: "eq"
  expected: "STARTING"

- condition: "${STATUS}"
  operator: "ne"
  expected: "STARTING"

- condition: "${STATUS}"
  operator: "in"
  expected: ["STARTING" , "BEGINNING"]
```

Just a suggestion

**Comment by yohamta0** [comment]
Here’s another design idea.
We could also implement a simple expression language like this:
```yaml
- condition: "${STATUS}=STARTING and ${step1.exitCode}=0"
- condition: "${STATUS}=STARTING or ${step1.exitCode}=0"
- condition: "(${STATUS}=STARTING or ${step1.exitCode}=0) and ${FOO}=FOO"
```

I'm considering allowing only `KEY=VALUE` pairs and logical operators like `and`/`or` to keep the implementation simple.
