### ISSUE TITLE
feat: artifact system for sharing files between steps

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#1027]
## Problem

Right now there's no built-in way to share files between DAG steps. You have to either use external storage or hack around with shared volumes. This makes common patterns like data pipelines or build processes more complicated than they need to be.

## Proposal

Add an artifact system where steps can save files that other steps can use. Keep it simple:

1. Each step gets an environment variable `$DAGU_ARTIFACTS` pointing to where it can save files
2. Other steps can reference these files using the existing variable syntax like `${stepname.artifacts['filename']}`

## How it would work

```yaml
steps:
  - name: build
    command: |
      go build -o app
      cp app "$DAGU_ARTIFACTS/"
      
  - name: test
    command: |
      "${build.artifacts['app']}" --version
      ./run_tests.sh "${build.artifacts['app']}"
    depends: build
```

## Implementation notes

- Need to extend StepInfo to include artifacts map (filename -> path)
- Create artifact directories before running each step
- Scan artifact dir after step completes and populate the map
- Make sure it works with all executors (docker, ssh, etc)
- Use same retention policy as logs

## Why this matters

This would make Dagu much better for:
- Data pipelines (pass CSVs, parquet files between steps)
- ML workflows (share models, datasets)
- Build/deploy pipelines (pass compiled binaries, docker images)
- Any workflow where you're generating files

Basically any time you need to pass more than just text output between steps.

## Questions to figure out

- Should we limit artifact size? Or total size per DAG run?
- Do artifacts get cleaned up with histRetentionDays like logs?
- What happens if two steps write the same filename?

Let me know what you think. Happy to help implement this if there's interest.
