### ISSUE TITLE
feat: distributed child DAG execution via runners

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#1028]
Looking to distribute child DAG execution across different machines.

**Current state**

- Child DAG execution via `run` field in steps
- Existing queue system for DAG runs
- File-based architecture with shared state

**Proposed design**

Allow child DAGs to run on different machines by extending the queue system:

```yaml
steps:
  - name: preprocess
    run: preprocessing
  - name: train-model
    run: training
---
name: preprocessing
workerSelector:
  type: cpu-large
steps:
  - name: task
    command: task.py
---
name: preprocessing
workerSelector:
  gpu: true
steps:
  - name: task
    command: task.py
```

**Implementation plan**

1. Enhance DAG Queue: Current queue handles only root DAG runs. When a step has `nodeSelector`, instead of running child DAG locally, enqueue it with selector requirements.

2. Node Mode: New `dagu node` command that:
- Create heartbeat files to share the status of runners with other Dagu processes
- Watches queue for DAGs matching its capabilities
- Runs entire DAGs (not individual steps) as a child DAG
- Updates status/logs to shared filesystem

3. Minimal changes: 
- Add `workerSelector` field to Step struct
- Modify child DAG executor to check for workerSelector
- If present, enqueue instead of running it locally
- Worker pulls and runs complete DAGs
- If certain timeout (e.g., 1 minutes) has passed, set the step status to error

**Example worker**

```bash
# GPU worker
dagu worker --label gpu=true --label memory=64G

# CPU worker  
dagu worker --label cpu-large --label region=us-east
```

Alternative wording: `worker`

**Requirements**

- Shared filesystem between all runners and agents (NFS, etc)
- Runners must have access to child DAG definitions
- Logs/status written to shared locations

This approach allows distributed DAG execution at step level, keeping complexity low.

Requested by Clément Doumouro
