### ISSUE TITLE
Issue in Web UI when loading bundle.js with docker compose installation

### ISSUE THREAD

**Issue by jhuang732** [dagu-org/dagu#1032]
![Image](https://github.com/user-attachments/assets/d26d8c53-f36b-4864-9889-476fd89585d1)

I'm unable to load the UI properly. This is the config in docker compose
```
  dagu:
    image: "ghcr.io/dagu-org/dagu:1.17.0"
    container_name: dagu
    hostname: dagu
    ports:
      - "8080:8080"
    environment:
      - DAGU_BASE_PATH=/dagu 
    volumes:
      - ./dagu_config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0:0"
    entrypoint: []
```

What am I missing?
