### ISSUE TITLE
HTTP executor only writes to stderr, does not populate output variables after update to 1.17.0

### ISSUE THREAD

**Issue by nightly-brew** [dagu-org/dagu#1040]
Hi,
After upgrading to 1.17.0, I've been having multiple issues with the HTTP executor.

Let's take this example dag

```yml
steps:
  - name: echo_works
    command: echo "Echo works"

  - name: echo_into_var
    command: echo "Echo works in var"
    output: ECHOVAR

  - name: echo_from_var
    command: echo "${ECHOVAR}"

  - name: test_200
    command: GET https://httpstat.us/200
    executor:
      type: http
      config:
        timeout: 10
        silent: true
        headers:
          Accept: application/json
    output: RET200

  - name: ret_200
    command: echo "${RET200}"

  - name: test_500
    command: GET https://httpstat.us/500
    executor:
      type: http
      config:
        timeout: 10
        silent: true
        headers:
          Accept: application/json
    continueOn: 
      failure: true
    output: RET500

  - name: ret_500
    command: echo "${RET500}"

  - name: test_404
    command: GET https://httpstat.us/404
    executor:
      type: http
      config:
        timeout: 10
        silent: true
        headers:
          Accept: application/json
    continueOn: 
      failure: true
    output: RET404

  - name: ret_404
    command: echo "${RET404}"
```

In this, I expect at leat the step test_200 to successfully populate RET200 with the json payload from the http response.
I am not sure if I should expect the same from test_500 and test_404, but it would make sense I think in combination with REST APIs.

However, running the above dag leads to the result below

![overall run outcome](https://github.com/user-attachments/assets/71f17b4d-8e43-4140-a8fb-c4997ec562de)

Even though test_200 does not fail, the response body is logged to stderr, RET200 is not populated either

![test_200 stdout log is empty](https://github.com/user-attachments/assets/2b05dec5-25ec-4982-adca-0b9a441c7441)

![test_200 stderr shows the payload](https://github.com/user-attachments/assets/0036482c-94c4-4f04-982c-0c4201b949eb)

![RET200 is not populated](https://github.com/user-attachments/assets/5fefc959-3389-4667-93a8-7d9185311c38)

test_500 and test_404 suffer the same fate.

Other tests in steps titled "echo_" do work as expected, so it looks like the issue only affects  HTTP executor.
