### ISSUE TITLE
feat: enhance repeatPolicy with explicit while/until modes

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#1043]
The current `repeatPolicy` has implicit behavior that changes based on configuration:
- `condition` + `expected`: Repeats **until** condition matches expected
- `condition` only: Repeats **while** condition returns exit code 0
- `exitCode`: Repeats **while** exit code matches

This implicit behavior is confusing. For example, to monitor while a service is "RUNNING", you have to think backwards and set it to repeat until it's NOT running.

## Solution

Add an explicit `mode` field to `repeatPolicy`:

```yaml
# Clear intent: repeat WHILE status is RUNNING
steps:
  - name: monitor-service
    command: check_status.sh
    output: STATUS
    repeatPolicy:
      repeat: while
      condition: "${STATUS}"
      expected: "RUNNING"
      intervalSec: 30
```

**Examples**

```yaml
# Wait UNTIL service is ready
repeatPolicy:
  repeat: until
  condition: "nc -z localhost 8080"
  intervalSec: 5

# Retry WHILE failing
repeatPolicy:
  repeat: while
  exitCode: [1]
  intervalSec: 10
  limit: 5

# Monitor WHILE healthy
repeatPolicy:
  repeat: while
  condition: "curl -f http://localhost/health"
  intervalSec: 60
```

**Implementation**

- [x] Update `repeat` field type in `RepeatPolicy` struct to `RepeatMode`
- [x] Accept constants values: `while` or `until`
- [x] Maintain backward compatibility by inferring mode when not specified:
   - `repeat: true` or unspecified (empty) -> defaults to `while`
- [x] Add [integration test](https://github.com/dagu-org/dagu/tree/main/internal/integration)
- [x] Update [the json schema](https://github.com/dagu-org/dagu/blob/main/schemas/dag.schema.json)
- [ ] Update API schema (v2)
- [ ] Update the Web UI to display `RepeatMode`
- [ ] Update the documentation on repeat policy

**Benefits**

- Clear Intent: No more mental gymnastics to invert logic
- Better DX: `repeat: while` is self-documenting

I’d appreciate any thoughts or suggestions you might have about this feature.

**Comment by thefishhat** [comment]
I'm working on this!

**Comment by thefishhat** [comment]
Do we want the existing modes

* condition + expected: Repeats until condition matches expected
* condition only: Repeats while condition returns exit code 0
* exitCode: Repeats while exit code matches

to also work without `repeat: while/until`? I'd vote for enforcing the `repeat` in these cases, making it a breaking change, for clarity. Thoughts?

**Comment by yohamta0** [comment]
@thefishhat Thank you so much for jumping on this issue!

Would it make sense to always default to `repeat: while` when no mode is specified? Enforcing repeat is reasonable, but I’d like to avoid a breaking change that could block existing DAGs, especially since the editor doesn’t currently shows validation errors well.

With this default (mode omitted → while):
- condition + expected: Repeats **while** condition matches expected
- condition only: Repeats **while** condition returns exit code 0
- exitCode: Repeats **while** exit code matches

What do you think?

**Comment by thefishhat** [comment]
What about the other way around? Should we invalidate DAGs that have `repeatPolicy` set to while/until but no accompanying condition/exitcode?

**Comment by yottahmd** [comment]
Yes, I agree that the other way around is more intuitive and makes more sense. Let's proceed with that direction.

> Should we invalidate DAGs that have repeatPolicy set to while/until but no accompanying condition/exitcode?

Thanks for thinking this through. How about we treat it as an indefinite loop?

For instance, some DAGs can have a step that repeats indefinitely:
```yaml
steps:
  - name: s1
    repeatPolicy:
      repeat: true
```

To clarify the complete behavior, I'd like to propose the following specification. Does these make sense? Apologies for the initial specification being incomplete.

1. Default mode (`untile`): **when mode omitted**
  - condition + expected: Repeats **until** condition matches expected
  - condition only: Repeats **until** condition returns exit code 0
  - exitCode: Repeats **until** exit code matches

2. While mode: **when `mode` is set `true` or `while` with `condition` or `exitCode`
  - condition + expected: Repeats **while** condition matches expected
  - condition only: Repeats **while** condition returns exit code 0
  - exitCode: Repeats **while** exit code matches

2. Indefinite (`always`) Mode: **when `mode` is set `true` and both `condition` and `exitCode` is omitted**

**Comment by yohamta0** [comment]
@thefishhat  Yes, I agree that the other way around is more intuitive and makes more sense. Let's proceed with that direction.

> Should we invalidate DAGs that have repeatPolicy set to while/until but no accompanying condition/exitcode?

Thanks for thinking this through. How about we treat it as an indefinite loop?

For instance, some DAGs can have a step that repeats indefinitely:
```yaml
schedule:
  start: "0 0 * * *"
  stop: "8 0 * * *"
steps:
  - name: s1
    command: data_processing.py
    repeatPolicy:
      repeat: true
      intervalSec: 30
```

To clarify the complete behavior, I'd like to propose the following specification. Does these make sense? Apologies for the initial specification being incomplete.

1. Default (`until`) mode: when `mode` omitted
  - condition + expected: Repeats **until** condition matches expected
  - condition only: Repeats **until** condition returns exit code 0
  - exitCode: Repeats **until** exit code matches

2. While mode: when `mode` is set `true` or `while` with `condition` or `exitCode`
  - condition + expected: Repeats **while** condition matches expected
  - condition only: Repeats **while** condition returns exit code 0
  - exitCode: Repeats **while** exit code matches

3. Indefinite (`always`)  mode: when `mode` is set `true` and both `condition` and `exitCode` omitted**
