### ISSUE TITLE
[Bug] Run Individual step of DAG does not work (local and remote)

### ISSUE THREAD

**Issue by jeremydelattre59** [dagu-org/dagu#1047]
Hi,
I just tested ticket #1015.
This feature doesn't work for me. I can see the API call returning a 200 code for the local server, but the task doesn't start running, and I don't have any logs in the file system. 
My wish in ticket #1015 was to be able to launch the steps manually even if it has never been launched automatically before (for example, to test a new workflow)

https://github.com/user-attachments/assets/8bbe0f68-0a92-422c-bf5a-abb83775ed49

On a remote Dagu, the RemoteNode parameter is not specified. Therefore, it returns a 400 error and nothing happens (same as #1003).

https://github.com/user-attachments/assets/3ed243f3-188f-4e47-bb64-03e0c1ef5895

Regards,
Jeremy

**Comment by thefishhat** [comment]
Interesting problem. Having a look now! 👀 

Also, apologies for your second point, I haven't tested the feature with a Remote dagu setup. 

**Edit:** First of all, there is a UI bug. The actions tab should not show up if the DAG has never been run. This is because what I implemented is a retry mechanism not a force run mechanism. If the DAG has never been run, then the retry should not be possible.

**Comment by thefishhat** [comment]
I raised a PR to add the absent `RemoteNode` query param and address the UI bug here: https://github.com/dagu-org/dagu/pull/1049. 

I wasn't able to reproduce your first issue on the local dagu setup @jeremydelattre59 ! This is the DAG I used:
```
name: Test
description: Test step repeat
group: ForTest
steps:
  - name: Initialize
    command: echo "Start Test"
  - name: step1
    script: |
      echo "$(date '+%Y-%m-%d %H:%M:%S') hello world !"
      sleep 10
    continueOn:
      failure: true
    depends:
      - Initialize
  - name: Done
    command: echo "Test Done"
    depends:
      - step1
```
Rerunning a step of a previously ran DAG works for me. The `Last Run` timestamp updates and I get the new logs. Could you please provide steps I can follow to recreate the issue locally?
