### ISSUE TITLE
When using ssh links, all output is captured as an error log

### ISSUE THREAD

**Issue by NebulaCoding1029** [dagu-org/dagu#1053]
```yaml
steps:
  - name: docker-pull
    executor:
      type: ssh
      config:
        user: xxx
        ip: xxx
        key: /xxx/key
    command:
      - cat /logs/tmp/pull_info.log 2>&1
    output: PULL_OUTPUT
```

Before the version upgrade, there was no problem, but when I updated the docker image, now all output is directed to ERR, even if it is a simple cat.

It's a great project, thank you to the development team！
