### ISSUE TITLE
feat：Thin log output or log cleanup

### ISSUE THREAD

**Issue by NebulaCoding1029** [dagu-org/dagu#1063]
It looks like dagu will persist all the logs locally, but some logs such as virus scan logs are very large, like my clamAV scan logs totaled 1G... At the moment my solution is to periodically delete expired logs in the mounted volume via ssh, but it doesn't feel very elegant, and I hope it can provide a related function.
Thank you very much for the hard work of the project team!

**Comment by yohamta0** [comment]
Hi @NebulaCoding1029, Thank you for the detailed suggestion. Since v1.17.0, Dagu automatically cleans up stdout and stderr log files when they are written to standard output.

You can adjust the retention period with histRetentionDays in DAG files:
Here's an example to set cleanup period:
```yaml
# Per-DAG
histRetentionDays: 7  # Keep 7 days

# Or global in base.yaml
histRetentionDays: 30  # Default
```

Does this solve the issue? Please let me know if it does not remove the outdated files in your system.
