### ISSUE TITLE
bug: scheduler discard items (v1.17.3)

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#1070]
test.yaml:
```
schedule:
  start: 
  - "17 * * * *"
  - "18 * * * *"
  - "19 * * * *"
  - "20 * * * *"
  - "21 * * * *"
  - "22 * * * *"
  - "23 * * * *"
  - "24 * * * *"
  - "25 * * * *"
  - "26 * * * *"
  - "27 * * * *"
steps:
  - name: hello world
    command: sh
    script: |
      echo "Hello, world!"
      
  - name: wait
    command: sleep 20
```

The scheduler executes the dag exactly once but then says:
```sh
time=2025-06-28T23:16:49.838+02:00 level=INFO msg="Scheduler started"
time=2025-06-28T23:17:00.842+02:00 level=INFO msg="Received item from queue" data=test:0197b866-86fd-7417-97bc-f972ad177c20
time=2025-06-28T23:17:01.345+02:00 level=INFO msg="Item is invalid, discarding" name=test dagRunId=0197b866-86fd-7417-97bc-f972ad177c20
```

Reported-by: Jochen
