### ISSUE TITLE
feat: Enable errexit (-e) flag by default for shell executors

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#1081]
## Problem Statement

Currently, when Dagu executes shell commands using sh, bash, or nix-shell, it does not enable the errexit (`-e`) flag by default. This means that if a command in a multi-line script fails, the script continues executing subsequent commands, which can lead to:

1. Silent failures where errors go unnoticed
2. Cascading issues when later commands depend on earlier ones
3. Inconsistent behavior compared to modern CI/CD systems
4. Users having to remember to add `set -e` manually to every script

### Current Behavior

```yaml
steps:
  - name: example
    command: |
      false  # This fails with exit code 1
      echo "This still executes"  # But this runs anyway
```

The step only fails if the *last* command fails. Users must explicitly add `set -e`:

```yaml
steps:
  - name: example
    script: |
      #\!/bin/bash
      set -e  # Must be added manually
      false
      echo "This won't execute"
```

### Proposed Change

Add the `-e` flag by default when constructing shell commands for sh, bash, and nix-shell executors. This would make shell scripts fail immediately when any command returns a non-zero exit code.

### Implementation Details

The change needs to be made in `/internal/digraph/executor/command.go`:

1. **For inline commands** (using `-c`): Change from `sh -c "commands"` to `sh -e -c "commands"`
2. **For script files**: Change from `sh script.sh` to `sh -e script.sh`
3. **For nix-shell**: Add `-e` flag to the shell invocation within nix-shell

Key locations:
- `shellCommandBuilder.Build()` method (lines 216-229 for default shells)
- `newCmd()` method (line 121 for script file execution)
- Special handling needed for nix-shell case (lines 187-202)

### Documentation Updates

- Update shell executor documentation to mention errexit is enabled by default
- Update examples to remove redundant `set -e` commands
- Document that users can disable errexit with `set +e` if needed for specific commands
