### ISSUE TITLE
proposal: Template-based YAML Parsing

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#418]
Implement a template-based YAML parsing system using Go's template package to enhance flexibility.

Example DAG Definition:
```yaml
description: This is an example DAG
schedule: "0 0 * * *"
env:
  - FOO: "FOO"
steps:
  - name: task1
    description: This is task 1
    command: echo {{env "FOO"}}
  - name: task2
    description: This is task 2
    command: echo {{env "FOO" | json}}
```
