### ISSUE TITLE
Support Self-Signed Certs with http Executor

### ISSUE THREAD

**Issue by mnmercer** [dagu-org/dagu#452]
Currently there isn't a way to use the http executor if you need to make a request to a site with a self-signed cert. I can accomplish something similar by using curl and the `-k` flag like so:
```yaml
- name: insecure http request
  command: sh
  script: |
    curl -k -s https://example.com/api/colors
  output: RESULT
```
But it would be great to use the `http` executor instead of this.

**Comment by mnmercer** [comment]
As a follow up to this, I cannot actually use the output of this type of curl request as an input to the `jq` executor. The actual request I am making returns formatted JSON, but if I have a step afterwards like this
```yaml
  - name: unmarshal
    depends:
      - insecure http request
    executor:
      type: jq
        config:
          raw: true
    command: '.test'
    script: "$RESULT"
    output: TEST
```
I get an error from the jq executor that says `Failed to start DAG: json: cannot unmarshal array into Go value of type map[string]interface {}`.

**Comment by mnmercer** [comment]
@bbqi Apologies, I meant to say that I had included the `-s` flag in the curl call in the first step. Even with that though, the `jq` executor still throws the same error.

**Comment by mnmercer** [comment]
@bbqi Wanted to bump up this issue as the latest Dagu Docker image does not have `curl` installed and thus we'd have to create a custom image to be able to do something that ideally the `http` executor should support by default.

**Comment by nightly-brew** [comment]
Since 1.17.0, wget is no longer part of the docker image as well.
After fixing the issue in #1040 , I am now facing the same problem as @mnmercer .

In my case, Dagu connects to various appliances in my network which make use of self signed certs on the REST API side.

Would it be possible to bump again this issue?

Thanks!

**Comment by yohamta0** [comment]
Hi @nightly-brew, thank you for raising this!
How about adding a `skipTLSVerify` flag to the http executor?

**Example:**
```yaml
  steps:
    - name: call internal API
      executor:
        type: http
        config:
          skipTLSVerify: true
          headers:
            Authorization: "Bearer token"
      command: get https://internal-api.example.com/data
```
If this looks good, I'll add this patch very soon. What do you think?
