### ISSUE TITLE
[Feature request] Option to run all steps sequentially

### ISSUE THREAD

**Issue by fishnux** [dagu-org/dagu#469]
Feature request: Option to run all steps sequentially

Some of my workflows make use of steps that run sequentially, so it would be better to have an option per-DAG to run all steps sequentially. This would facilitate things such as re-ordering steps as we don't have to change the depends property, but just move steps around 🙂

**Comment by yohamta** [comment]
I believe the `maxActiveRuns` option would be beneficial if you want to run steps sequentially. It sets the maximum number of steps that can run in parallel. For example:

```yaml
maxActiveRuns: 1

steps:
  ...
```

**Comment by rafiramadhana** [comment]
@fishnux sounds interesting, btw may I know how do we (as a user) define the sequence?

**Comment by yohamta0** [comment]
Sorry for keeping this issue open for a long time. This feature was implemented in version 1.17.x.
You can define a DAG with sequential steps like this:
```yaml
steps:
  - name: s1
    command: echo step1
  - name: s2
    command: echo step2
```
Result:
<img width="942" height="675" alt="Image" src="https://github.com/user-attachments/assets/292d23e6-2c54-426d-894f-c88eada42123" />

I'm closing but let us know if you have further request.
