### ISSUE TITLE
Adding queueing and batching while running multiple dags.

### ISSUE THREAD

**Issue by kriyanshii** [dagu-org/dagu#535]
I want to add additional status as **in queue**.
As we are using dagu for running multiple dags at the same time consuming 5min or more time. So what I wanted to do is, queue the dag processes. and it will run one by one. Do you have any insights on this?

**Comment by yohamta** [comment]
Currently Dagu doesn't have queue system. But we can achieve the same effect by combining multiple DAGs.
Suppose we want to queue Task1 execution:

Task1
```yaml
# run every minute
schedule: "* * * * *"

steps:
  #  check queue file and process
  - name: check
    # some work to do
```

Then we can have another DAG enqueue message when you want to run the Task1 via REST api etc.
This could be done by any other way

```yaml
params: "MSG"
steps:
  #  push message into a queue file
  - name: push
    command: bash
    script: |
      # append message to queue (database, redis, file, etc)
      echo $MSG > /tmp/task1-queue
```

I agree that having queueing mechanism would be great but could be a bit tricky.
Because Dagu doesn't have database right now.
