### ISSUE TITLE
feature request: foreach

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#550]
I'd like to add a feature that splits workflow execution into file-level units. By specifying a path in the `foreach` field of a step, subworkflow will be generated for each file matching that path. This will enable re-execution at the file level and simplify workflow management. 

Example:
```yaml
steps:
  - name: clean
    command: rm ./intermediate/*
  - name: create files
    command: create.py -o ./intermediate
    depends:
      - clean
  - name: process file
    foreach:
      files: ./intermediate/*
    command: process.py $FILE
    depends:
      - create files
```

call subworkflow:

```yaml
steps:
  - name: clean
    command: rm ./intermediate/*
  - name: create files
    command: create.py -o ./intermediate
    depends:
      - clean
  - name: process file
    foreach:
      files: ./intermediate/*
    command: run foo-workflow --params="$FILE"
    depends:
      - create files
```
