### ISSUE TITLE
Add `json` bool configuration option to HTTP executor

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#578]
**Overview**
Add a `format` option to the HTTP executor configuration.

```yaml
steps:
  - name: a step
    command: GET https://xxx
    executor:
      type: http
      config:
        format: json
    output: DATA1
```

This will format the result as standard JSON, including the status code and response headers:
```json
{
  "status_code": 200,
  "headers": [
    "xxx": "yyy"
  ],
  "body": {
    "some_field": "some_value"
  }
}
```

**Additional Context**
https://github.com/dagu-dev/dagu/discussions/577#discussion-6755295

EDIT: I changed the field type from `json: boolean` to an `format: string` for potential future options.
