### ISSUE TITLE
Add support for env variables in executor config

### ISSUE THREAD

**Issue by oyvinev** [dagu-org/dagu#674]
It would be very useful if one were able to use environment variables when configuring an executor - an example of desired usage with the ssh executor:

```
executor:
   type: ssh
   config:
       user: $SSH_USER
       ip: $SSH_HOST
       password: $SSH_PASSWORD
       port: $SSH_PORT
```

I'm not familiar enough with Go to neither understand the complexity nor attempt a PR of it.
