### ISSUE TITLE
Add `DAG_DETAILS_JSON` for access to DAG metadata within tasks

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#710]
Currently, accessing DAG details (like schedule, last run time, etc.) within tasks requires workarounds or potentially undocumented environment variables. This makes it difficult for tasks to react dynamically to DAG-specific information.

This issue proposes adding a new environment variable, `DAG_DETAILS_JSON`, which will contain a JSON representation of all relevant DAG metadata. This will provide a consistent and comprehensive way for tasks to access this information, especially useful for executors like `jq` that can easily parse JSON.

**Example Usage (with jq):**

```yaml
steps:
  - name: get schedule
    executor: jq
    command: '.schedule'
    script: "echo $DAG_DETAILS_JSON"
    output: DAG_SCHEDULE
```
