### ISSUE TITLE
Consider more idomatic docker config

### ISSUE THREAD

**Issue by chrishoage** [dagu-org/dagu#715]
While working on my PR I made extensive changes to the Dockerfile and I'm wondering if you think I should upstream them. 

- I added an `entrypoint.sh` which configured the environment
- Using the entrypoint allow the user to specify the DOCKER_GID and add `dagu` to the docker group
- Use su-exec to execute dagu as the dagu user
- Changed the home directory and DAGU_HOME to be `/config`. This is a more idiomatic way of handling docker container configs
- removed sudo and dagu in sudoers

What this allows for is a much cleaner docker compose setup. 

- No need to run a container o run socat and forward the docker socket. Just bind to to the container
- Allows users to load extra config though `/entrypoint.d/*.sh` (this is not done in my test branch, but could very easily be added. I have a lazy ADDITIONAL_PACKAGES but I don't think this should be shipped as is) 

You can look at my changes here https://github.com/chrishoage/dagu/commit/23eae41e4dc5a3fffe227c134e7cbd2936089443 and if any of these are worth upstreaming I can produce a PR with the parts you think would be a good fit for the official docker image. 

```yaml
services:
  caddy:
    image: caddy
    container_name: caddy
    hostname: caddy
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  dagu:
    image: ch/dagu
    container_name: dagu
    hostname: dagu
    volumes:
      - ./config:/config
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # - ADDITIONAL_PACKAGES=docker-cli deno bash
      - PUID=1000
      - PGID=1000
      - DOCKER_GID=970
      - DAGU_TZ=America/Los_Angeles
```

```Caddyfile
http://localhost {
  handle /dagu* {
    reverse_proxy dagu:8080
  }
}
```
