### ISSUE TITLE
Remote Node Support

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#730]
**Overview**
Add capability to manage multiple Dagu instances from a single UI, allowing users to monitor and control DAGs across different environments or servers.

**Feature Details**
- Enable configuring multiple Dagu instances (remote nodes) through admin.yaml
- Add UI dropdown to switch between instances
- Support proxying API requests to remote instances
- Maintain all UI functionality across remote instances

**Configuration Example**
```yaml
# admin.yaml
remoteNodes:
  - name: "prod"
    apiBaseUrl: "https://prod-dagu.example.com/api/v1"
  - name: "staging"
    apiBaseUrl: "https://staging-dagu.example.com/api/v1"
```
