### ISSUE TITLE
problem with Remote Node on v1.15.0

### ISSUE THREAD

**Issue by kamandir** [dagu-org/dagu#736]
hey there!

Thanks for the new nice stuff released! I started some testing and found challenges...
maybe it's me doing something wrong, but i will still report it to find out why it fails... ;)

whatever i do, all the time i hit this error (code 500) when try to change from local node to a remote. 
**Config:**
```
# Remote DAGU Nodes
remoteNodes:
 - name: "DEV" # Name of the remote node
   apiBaseUrl: "https://_my_dev_node_.com:8443/api/v1"
   isAuthToken: true
   authToken: "bla-bla...."
```

**Error:**
```
GET https://_my_dev_node_.com:8443/api/v1/dags?page=1&limit=50&searchName=&searchTag=&remoteNode=DEV 500 (Internal Server Error)

bundle.js?v=1.15.0:102 SyntaxError: Failed to execute 'json' on 'Response': Unexpected end of JSON input
    at bundle.js?v=1.15.0:102:167937
    at bundle.js?v=1.15.0:102:167601
    at Object.next (bundle.js?v=1.15.0:102:167706)
    at s (bundle.js?v=1.15.0:102:168109)
onError @ bundle.js?v=1.15.0:102
(anonymous) @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
a @ bundle.js?v=1.15.0:75
Promise.then
l @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
iX @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
setTimeout
onErrorRetry @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
a @ bundle.js?v=1.15.0:75
Promise.then
l @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
iX @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
(anonymous) @ bundle.js?v=1.15.0:75
il @ bundle.js?v=1.15.0:2
_l @ bundle.js?v=1.15.0:2
vl @ bundle.js?v=1.15.0:2
Ml @ bundle.js?v=1.15.0:2
(anonymous) @ bundle.js?v=1.15.0:2
yc @ bundle.js?v=1.15.0:2
lc @ bundle.js?v=1.15.0:2
jo @ bundle.js?v=1.15.0:2
(anonymous) @ bundle.js?v=1.15.0:2
bundle.js?v=1.15.0:102 
```

**Comment by yohamta** [comment]
@kamandir Thank you for submitting the issue! I’m trying to reproduce it, but everything seems to be working correctly in my environment.

1. Running server 1 on port 8080 and server 2 on port 8081.
2. Server 2 is configured with `IS_AUTHTOKEN=true AUTHTOKEN=123456`
3. The admin.yaml configuration is as follows:
```yaml
# admin.yaml
port: 8080
remoteNodes:
  - name: "dev"
    apiBaseUrl: "http://localhost:8081/api/v1"
    isAuthToken: true
    authToken: 123456
```
4. API requests with cURL
```bash
curl --location 'http://localhost:8080/api/v1/dags?remoteNode=dev'
```

With this setup, both the API and WebUI on localhost:8080 are working as expected.
Could you please share more details about your setup so I can better understand and reproduce the issue? Thanks! :)

**Comment by kamandir** [comment]
i'm running it on a secure port with a certificate installed. Does this make difference?..

**Comment by yohamta** [comment]
Thanks for the information! I'll try to fix.

**Comment by yohamta** [comment]
@kamandir Thanks for reporting the issue! I've released v1.15.1 that should fix the HTTPS connection problems.

You can now configure TLS verification skipping per remote node like this:
```yaml
remoteNodes:
 - name: "DEV"
   apiBaseUrl: "https://_my_dev_node_.com:8443/api/v1"
   isAuthToken: true
   authToken: "bla-bla...."
   skipTLSVerify: true  # Add this line if you need to skip TLS verification
```
Please try it out and let me know if you're still experiencing any issues. Thanks for helping improve Dagu! 🙂
