### ISSUE TITLE
Support `variable` field & Go template syntax

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#738]
**Overview**
Parse most ofthe fields using `template/text` package in Go. Add utility functions from [`sprig`](https://masterminds.github.io/sprig/).

Example:
```yaml
name: example
variables:
  NAME: "World"
steps:
  - name: hello
    command: "Hello, {{.NAME}} !"
```
