### ISSUE TITLE
dag: Support Defining `params` as a list of key-value pairs in YAML Configuration

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#755]
Currently, Dagu allows defining parameters in the params field as a space-separated string, which can be limiting. To enhance flexibility and readability, allow `params` to be defined as a map (dictionary) in the YAML configuration.

Current definition example:
```yaml
params: param1=value1 param2=value2

steps:
  - name: example_step
    command: |
      echo Parameter 1: ${param1}, Parameter 2: ${param2}
```

Proposed Definition Example:
```yaml
params:
  param1: value1
  param2: value2

steps:
  - name: example_step
    command: |
      echo Parameter 1: ${param1}, Parameter 2: ${param2}
```
