### ISSUE TITLE
dag: Add support for Slack notification in DAG definitions

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#758]
This feature introduces a new `slackOn` configuration field that allows users to enable Slack alerts for DAG execution events such as success and failure. Users can define webhook URLs for each event.

Example:
```yaml
slackOn:
  success: true
  failure: true
slack:
  success:
    webhookUrl: https://hooks.slack.com/services/T00000000/B00000000
  failure:
    webhookUrl: https://hooks.slack.com/services/T00000000/B00000000
```
