### ISSUE TITLE
dag: Support `precondition` as a shell command

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#768]
Currently it only accepts string matching preconditions. I'd like to improve it to accept only shell command and check the exit value if it start executing the DAG / step.

Example:
```yaml
precondition: "test -f somefile"

steps:
  - name: step1
    precondition: "test -f somefile"
```

Multiple conditions
```yaml
precondition:
  - "test -f file1"
  - "test -f file2"

steps:
  - name: step1
    precondition:
      - "test -f file1"
      - "test -f file2"
```
