### ISSUE TITLE
dag: Support step `continueOn` based on command output matching

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#769]
# Background
Currently, the `continueOn` configuration for DAG steps only supports static conditions like exit codes. There's a need to make this more dynamic by allowing continuation decisions based on the actual command output.

# Proposed Feature
Add support for output-based conditions in the `continueOn` configuration. This would allow steps to continue execution even after a failure if the command output matches specified patterns.

```yaml
steps:
  - step 1
    command: echo hello
    continueOn:
      exitCode: [0,1] # continue on if the exitcode is one of these
  - step 2
    command: echo hello
    output: FOO
    continueOn:
      condition: "$FOO"
      expected: # continue on if $FOO contains one of the expected texts
        - "hello"
        - "bye"
```
