### ISSUE TITLE
Executors for Database read / write

### ISSUE THREAD

**Issue by accforgithubtest** [dagu-org/dagu#789]
Hello, just discovered dagu, and seems a like neat lightweight tool - thank you for creating it!

Is there any way for me to save the results of a http executor to a postgres / mariadb database ?
I have seen examples for using the http executor, however there are no examples of saving any data to a database. 

Is this currently possible ? If yes, may I pls request to add an example using postgres / mariadb to the docs.
Cheers!

**Comment by yohamta** [comment]
Hi, thanks for your interest and kind words!

While there isn't a direct function to interact with the database, there are a few ways to accomplish what you want to do.

Here are some example DAGs:

### 1. Run python script
```yaml
steps:
  - name: make_http_request
    executor:
      type: http
      config:
        timeout: 10
        silent: true
    command: GET https://api.example.com/data
    output: HTTP_RESULT

  - name: save_to_database
    command: python
    depends: make_http_request
    script: |
      import psycopg2
      import json
      import os
      
      # Python program to insert data to the database
```

### 2. Uses Docker executor to run database operations

```yaml
steps:
  - name: make_http_request
    executor:
      type: http
      config:
        silent: true
    command: GET https://api.example.com/data
    output: HTTP_RESULT

  - name: save_to_database
    depends: make_http_request
    executor:
      type: docker
      config:
        image: postgres:17-alpine
        autoRemove: true
        container:
          env:
            - PGHOST="$DB_HOST"
            - PGPORT="$DB_PORT"
            - PGDATABASE="$DB_NAME"
            - PGUSER="$DB_USER"
            - PGPASSWORD="$DB_PASS"
    command: psql -c "INSERT INTO some_table (response_data) VALUES ('$HTTP_RESULT');"
```

Hope that helps!

**Comment by accforgithubtest** [comment]
Thank you for the reply @yohamta ! I guess writing few libes of python code is a way of trying this out.

Is a proper database executor in the roadmap ? Can i make this a feature request for a database executor please ?

Ideally, a named database connection could be created via environment variables in docker compose (`DATABASE_TESTDBNAME=postgres://user:password@host:port`), and an executor that can do something like 

```yml
- name: execute_sql
  depends: make_http_request
  executor:
    type: docker
    config:
      connection: DATABASE_TESTDBNAME
      sql: |
        select * from ......
```

**Comment by yohamta** [comment]
This looks useful, so I would be grateful if you could write a Feature request.
While reading environment variables from `docker-compose.yaml` is convenient, it could potentially be a footgun.

Would it be acceptable to define commonly used environment variables in `~/.config/dagu/base.yaml` like this?

```yaml
env:
  - DATABASE_TESTDBNAME1: "postgres://user:password@host:port"
  - DATABASE_TESTDBNAME2: "mariadb://user:password@host:port"
```

Also, regarding the SQL execution executor, what are your thoughts on this format?

```yaml
- name: execute_sql
  depends: make_http_request
  executor:
    type: sql
    conn: ${DATABASE_TESTDBNAME1}
  script: |
    insert into table ...
```

I would appreciate your feedback on these suggestions! I'm also open to alternative ideas or recommendations. :)

**Comment by yohamta** [comment]
Great point. I was thinking we could introduce `format` field for `sql` step output:

```yaml
- name: execute_sql_1
  depends: make_http_request
  executor:
    type: sql
    config:
      dsn: ${DATABASE_TESTDBNAME1}
      format: json # options: json, csv, or raw
  script: |
    select * from .... where id in (<data from http request>)
  output: SQL_OUT_1
```
(sorry! I've updated the config format a bit)

> This is just an example to see how a SQL chaining feature, if possible, would work in dagu.

Yes, that's a really interesting idea! While I think the `select * from (SQL_OUT_1)` approach is useful and feasible, we'd need to figure out how to handle SQL properly. We could use SQLite under the hood or possibly integrate with `dbt`? Just thinking out loud here, I'd love to hear your thoughts on this.
