### ISSUE TITLE
Support for Retry on Custom Exit Codes

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#792]
It would be helpful to have a feature that allows retrying a task based on custom exit codes. This feature would specify certain non-zero exit codes where retries should occur, while other non-zero exit codes would cause the task to fail immediately.

Example configuration:
```yaml
steps:
  - name: retryable task
    command: main.sh
    retryPolicy:
      limit: 3
      intervalSec: 5
      exitCode: [1, 2]  # Retries if the exit code is 1 or 2; otherwise, the task fails.
```
