### ISSUE TITLE
Add Attachment Support for Mail Executor

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#812]
Currently, the mail executor sends plain text emails without file attachments. We should extend its functionality to include an `attachments` field in the configuration, allowing users to specify one or more file paths to attach to outgoing emails.

**How to Implement:**

1. **Extend the Configuration Schema:**  
   Add an `Attachments` field (a slice of strings) to the mail executor’s configuration structure. For example:
   ```go
   type MailExecutorConfig struct {
       To          string
       From        string
       Subject     string
       Message     string
       Attachments []string
   }
   ```

2. **Update the Mail Sending Logic:**  
   Modify the [mail executor code](https://github.com/dagu-org/dagu/blob/main/internal/digraph/executor/executor.go) that builds and sends the email to loop through the `Attachments` list and attach each file. Be sure to include file existence checks and error handling.

3. **Update Documentation and Examples:**  
   Add an example in the documentation to show how to use the new field in a DAG file.

**Example Usage in a DAG File:**
```yaml
steps:
  - name: send report
    executor:
      type: mail
      config:
        to: user@example.com
        from: no-reply@example.com
        subject: "Daily Report"
        message: "Attached is the daily report."
        attachments:
          - /tmp/report.csv
          - /tmp/summary.png
```
