### ISSUE TITLE
[bug] set dagsDir in config not applied

### ISSUE THREAD

**Issue by triole** [dagu-org/dagu#840]
Thanks for the `--config` fix. I really enjoy using dagu and appreciate your great work.

Playing with the configuration I just discovered one tiny thing. If you set the `dagsDir` inside a config file the setting does not seem to be applied. It is not a critical problem because I decided to use the command line arg `--dags`, which works fine. Nonetheless the documentation states, that also the config file could be used to set the dagsDir. 

I think there are two possibilities to go on from here and I am happy to leave you the choice...

1. Fix the config setting `dagsDir`, which probably would be a little cleaner because the other dir settings in the config file seem to work.
2. update the documentation, remove the part about the `dagsDir` and write that the cli arg `--dags` is the way to go

As I said thank you for you quick reactions to the issues and the marvellous tool you have given us. Please let me know in case I got something wrong. Have a nice day.

**Comment by triole** [comment]
I was playing around a little bit and stumbled across the fact that one directories can only be configured through env variables. Wouldn't it be nice if all the settings that could be applied by env vars would also be available inside the config. I tried the following inside my config and it did not work because the log dir for example was not set.

```yaml
adminlogDir: /home/usr/data/adminlog
dagsDir: /home/usr/conf/dags
dataDir: /home/usr/data/data
logDir: /home/usr/data/log
suspendflagsDir: /home/usr/data/suspend
workDir: /home/usr/data/work
```

Just as a suggestion. I would appreciate a config working like that. Thanks.
