### ISSUE TITLE
Basic auth not working when token auth is enabled

### ISSUE THREAD

**Issue by topjor** [dagu-org/dagu#880]
I just updated from 1.16.0 to 1.16.4 and I can not use the webUI anymore.

I have both token authentication and basic authentication enabled. The webUI itself loads but data fetching is not working. The browser does not ask for basic authentication like it did before.

After inspecting the requests, I am receiving 401's for the API calls with the `Www-Authenticate` header set to `Bearer realm="restricted"`

Further testing the API directly with my configured basic auth credentials also does not allow me access to the API. The configured token is working correctly for the API.

my configuration looks as follows:
``` yaml
isBasicAuth: true
basicAuthUsername: topjor
basicAuthPassword: RedactedPassword

isAuthToken: true
authToken: RedactedToken

navbarTitle: main01.truenas
```

**Comment by topjor** [comment]
After a little bit of more inspection and testing, The old basic auth properties are not respected. The old token options are working, which is why I get the 401's.

The new basic auth configuration options are working properly if I migrate to them:

``` yaml
auth:
  basic:
    enabled: true
    username: topjor
    password: RedactedPassword
```
