### ISSUE TITLE
Output VARS no longer expand/shown in UI as input to other steps

### ISSUE THREAD

**Issue by mdanilakis** [dagu-org/dagu#916]
Given a simple DAG:

```
steps:
  - name: step1
    command: echo "foo"
    output: RESULT
  - name: step2
    command: ./myscript.sh $RESULT
    depends:
      - step1
```

In version 1.12.9 we were able to see the evaluation of `$RESULT` as Args in the UI, but in recent versions this no longer works. This is super helpful when debugging DAGs.

<img width="718" alt="Image" src="https://github.com/user-attachments/assets/397958a6-66b8-4f1e-99aa-777402026195" />

Is anyone else experiencing this? Happy to deep dive and see what changed or understand if this is intentional.
