### ISSUE TITLE
Params interpreted differently breaking workflows

### ISSUE THREAD

**Issue by mdanilakis** [dagu-org/dagu#917]
Given the DAG:

```
params: REQUEST_BODY={}
steps:
  - name: get_param_using_jq
    executor:
      type: jq
      config:
        raw: true
    command: '.MyParamArr'
    script: ${REQUEST_BODY}
    output: MY_PARAM_ARR
  - name: print_param
    command: echo $MY_PARAM_ARR
    depends:
      - get_param_using_jq
```

In version 1.12.9, the `$MY_PARAM_ARR` can be fed into scripts and works seamlessly, in newer versions (e.g. 1.16.2) this is broken:

Working:
<img width="847" alt="Image" src="https://github.com/user-attachments/assets/ea743317-94ee-4850-a8ae-1fb91f9eb074" />

Not working in `1.16.2`
<img width="595" alt="Image" src="https://github.com/user-attachments/assets/9cf873dc-b6d4-45a2-928b-7a4a502e40fb" />
