### ISSUE TITLE
Conditions no longer work with backtick evaluation

### ISSUE THREAD

**Issue by mdanilakis** [dagu-org/dagu#919]
```
preconditions:
      - condition: "`test -f /some/path/${TO}/a/file/foo.mp4`"
```

This used to work as expected in `1.12.9`, in newer versions it breaks the UI.

**Comment by yottahmd** [comment]
@mdanilakis Thank you for reporting the issue. Could you please try using the `command` field instead?  
When the `condition` field is used, it also requires an `expected` field to compare the result, and the command inside the backticks in the `condition` value must exit with a status code `0`.  
In contrast, the `command` field simply checks the exit status. If it returns `0`, the condition is considered met.

```yaml
steps:
  - name: step1
    command: echo hello
    precondition:
      - command: "`test -f /tmp/a`"
```

Alternatively:

```yaml
steps:
  - name: step1
    command: echo hello
    precondition: "`test -f /tmp/a`"
```
