### ISSUE TITLE
Request:  Using nix-shell as dag command

### ISSUE THREAD

**Issue by eugenechyrski** [dagu-org/dagu#925]
I would like to run a dag which should be executed in a nix shell environment
Initial idea was to run something like 
```yaml
steps:
  - name: test-nix
    command: nix-shell -p git --run "bash"
    script: |
      git --version
```
But here git command is not found
Another attempt was to run 

```yaml
steps:
  - name: test-nix
    command: |
      nix-shell -p git  --run bash <<EOF
      echo "all good" | grep all
      EOF
```
But here pipe does not work

So i am curious if there is a clean approach to have a dag with a nix-shell command defining required  packages and to run a command in that created environment?   I do not want to create additional script files or shell.nix files.

**Comment by yottahmd** [comment]
@eugenechyrski Can you try using `shell` field in a step?
```yaml
steps:
  - name: test-nix
    command: git --verision
    shell: nix-shell
```
 Or you can set `SHELL` environment in the DAG file as follows:
```yaml
env:
  - SHELL: "nix-shell"
```

**Comment by yottahmd** [comment]
@eugenechyrski Thanks for the detailed explanation. That makes sense.

Sure, we’ll add first-class support for `nix-shell` in an upcoming version of Dagu.

**Planned design:**
```yaml
steps:
  - name: test-nix
    command: git --version
    shell: nix-shell
    packages:
      - git
```
