### ISSUE TITLE
Enhance `RepeatPolicy` field

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#939]
Document about repeat policy:
https://dagu.readthedocs.io/ja/latest/yaml_format.html#repeat-steps

We would like to enhance this functionality as follows:
- Add condition to repeatPolicy until a certain condition is satisfied
  Add `condition` setting to the step

```
step:
- name: step1
  command: xxx
  repeatPolicy:
    condition: "foo"
    expected: "bar"
    intervalSec: 30
```

**Comment by ghansham** [comment]
Custom exir code documentation can also be added in retry clause

**Comment by yottahmd** [comment]
Thanks! Updated the design.

**Comment by thefishhat** [comment]
Does `ExitCode` here mean repeat **until** command exit code matches, or repeat **while** command exit code matches?

**Comment by yottahmd** [comment]
Hi @thefishhat, it continues to repeat **while** the command's exit code matches.

**Comment by thefishhat** [comment]
Thanks @yottahmd ! Two more questions about the design:
* Should `3. Command (new)` condition also be covered in backticks, since it is also a shell command - similar to 2. This makes the spec more consistent and the code is easier to implement.
*  For `1. Simple string matching (new)` I assumed that the output of command is matched against `expected`. But what is `condition` used for in this case? Right now in my draft implementation it remains ignored for this use case.

**Comment by yottahmd** [comment]
@thefishhat Thank you for raising these thoughtful points!

* I agree the current wording can be confusing. I was planning to align the new behavior with the existing [Precondition](https://dagu.readthedocs.io/en/latest/schema.html#id6) field:

  1. When **both** `condition` and `expected` are set, treat the pair as a *text-match* test.
  2. When **only** `condition` is set, treat it as a *command* (no back-tick expansion). Keep repeating the step as long as the command exits with `0`.

  The current `Precondition` implementation is here. What do you think?
  [https://github.com/dagu-org/dagu/blob/51102e5d3c80cf66b7c8771d3b1df4c47c4df657/internal/digraph/scheduler/condition.go#L60](https://github.com/dagu-org/dagu/blob/51102e5d3c80cf66b7c8771d3b1df4c47c4df657/internal/digraph/scheduler/condition.go#L60)

* I was thinking the `condition` will usually reference an environment variable. So it needs to be used in evaluation. Example:

```yaml
steps:
  - name: repeat
    command: "python main.py"
    output: "RESULT"
    repeatPolicy:
      condition: "$RESULT"
      expected: "failed"
      intervalSec: 30
```

Now that I see it written out, the current design may still cause confusion 😅  I'd welcome your opinion on a clearer alternative.
