### ISSUE TITLE
race condition while using retry functionality

### ISSUE THREAD

**Issue by kriyanshii** [dagu-org/dagu#970]
While running this DAG it seems race condition happens to open the logfile.

YAML to reproduce the bug.
```
  steps:
    - name: api call
      command: sh main.sh 
      retryPolicy:
        limit: 3
        intervalSec: 1
        exitCode: [0, 1]  # Retry on rate limit and service unavailable errors

```

![Image](https://github.com/user-attachments/assets/a7f40c6e-92d9-44a2-8dfd-c23621063f0b)
