### ISSUE TITLE
feat: Add support for accessing step exit codes in subsequent steps and preconditions

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#986]
Currently, when a step fails but continueOn allows the DAG to continue, there's no native way to access the previous step's exit code in subsequent steps. This forces users to use shell script workarounds to handle conditional
logic based on exit codes.

**Use Case**

In horizontally wide DAGs with many parallel steps, users need to:
1. Allow certain non-zero exit codes to continue (using continueOn)
2. Make decisions in subsequent steps based on the specific exit code from previous steps

**Example scenario:**
- Step n: If exit code is not 0 or 40, fail the step. Include 40 in continueOn exit codes to allow continuation.
- Step n+1: Execute only if step n's exit code is 0. Skip if it's anything else (including 40).

**Proposed Solution**

1. Store exit codes at DAG-run level: Maintain a virtual dictionary storing exit codes for all steps (focusing on non-zero exit codes for efficiency).
2. Access syntax: Allow steps to access exit codes via special syntax:
`${steps["stepName"].exitCode}`
3. Example implementation:
```yaml
steps:
- name: step1
  command: some_work.py
  continueOn:
    exitCode: [40]  # Allow continuation on exit code 40

- name: step2
  command: some_work2.py
  preconditions:
    - condition: ${steps["step1"].exitCode}
      expected: "0"  # Only run if step1 succeeded
```

**Technical Requirements**

- Support both list and dictionary step formats
- Maintain incremental state snapshots at each step for reconstruction
- Only store non-zero exit codes to optimize memory usage
- Make exit codes accessible in:
  - Preconditions
  - Environment variables
  - Command substitution

**Benefits**

- Eliminates need for shell script workarounds
- Enables more sophisticated error handling patterns

Discussion Points

- Should we store all exit codes or only non-zero ones?
- What's the best syntax for accessing nested step data?
- Should this be extended to capture other step metadata (start time, end time, etc.)?

---
Reported-by: ghansham_san
