### ISSUE TITLE
feat: Add Parallel Execution Support for Steps and Child-DAGs

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#989]
Add ability to run the same step (command or sub-DAG) multiple times in parallel with differentparameters.

**Motivation**

Currently, to process multiple items, users need to either:
- Create multiple similar steps manually
- Use external scripts with loops
- Run items sequentially

This feature would enable:
```yaml
steps:
  - name: get-files
    command: find /data -name "*.csv" -printf "%f\n"
    output: FILES

  - name: process-files
    run: python process.py /data/${ITEM}
    parallel: ${FILES}
    maxConcurrent: 10
```

**Basic usage**
```yaml
# Simple array
parallel: ["file1", "file2", "file3"]

# From previous step
parallel: ${FILES}

# With parameters
parallel:
  - SOURCE: s3://customers
    TYPE: csv
  - SOURCE: s3://products
    TYPE: json
```

**Configuration options**
```yaml
parallel:
  items: ${ITEMS}
  maxConcurrent: 5      # Default: 10
  continueOnError: true # Default: false
```

**Key Design Decisions**

1. Special variable: ${ITEM} (uppercase to match DAG_NAME, DAG_RUN_ID pattern)
2. Default concurrency: 10 (safe default, prevents system overload)
3. Auto-detection: Automatically detect command vs sub-DAG based on run value
4. Output aggregation: Results available as array in ${RESULTS}

**Examples**

Process files in parallel

```yaml
steps:
  - name: process-all-regions
    run: workflows/deploy-region
    parallel: ["us-east-1", "eu-west-1", "ap-south-1"]
    params:
      - REGION: ${ITEM}
    maxConcurrent: 2

Dynamic parallel execution

steps:
  - name: get-tasks
    command: |
      echo '[
        {"id": "task1", "script": "process.py"},
        {"id": "task2", "script": "analyze.py"}
      ]'
    output: TASKS

  - name: run-tasks
    run: python ${ITEM.script} --task-id ${ITEM.id}
    parallel: ${TASKS}
```

Any questions or feedback will be very welcomed!
