### ISSUE TITLE
feat: flexible queue control

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#992]
**Why**

* Local/dev runs shouldn’t spawn extra workers.
* Teams may want a global concurrency cap.
* Individual DAGs sometimes need dedicated queues.

**What**

1. **Global on/off switch**

   * `queues.enabled` in `dagu.yaml` (default `true`)
   * Env override: `DAGU_QUEUE_ENABLED=false`

2. **Global queue settings**

   * `queues.config[].name`
   * `queues.config[].maxActiveRuns` (immutable per DAG)
     * This value cannot be overridden by individual DAGs when it's specified in global queue settings

3. **Per‑DAG queue name**

   * YAML field `queue: <name>`

**Config example**

```yaml
queues:
  enabled: true
  config:
    - name: globalQueue
      maxActiveRuns: 5
```

**DAG example**

```yaml
queue: differentQueue
```
