### ISSUE TITLE
feat: Support multiple DAGs in a single YAML file

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#994]
Allow defining multiple DAGs in a single YAML file using document separators (`---`). This reduces file proliferation when working with small, related workflows. This feature will be useful for writing a DAG that runs multiple child DAGs using `parallel` field because user don't need to create separate files for child DAGs that only contains small definitions.

### Example
```yaml
# workflows.yaml
name: main-pipeline
steps:
  - name: process
    run: transform-data    # References DAG below
    parallel: ["data_1", "data_2", "data_3"]

---
name: transform-data
steps:
  - name: transform
    command: transform.py
```

**Implementation**
- Use standard YAML document separators
- Each Child DAG must have unique `name` field
- Child DAGs referenced by name only
- Backward compatible with single-DAG files
