### ISSUE TITLE
feat: Add sequential execution mode for DAGs

### ISSUE THREAD

**Issue by yottahmd** [dagu-org/dagu#998]
Add a new mode field at the DAG level to support sequential step execution without requiring explicit
 dependencies.

**Current behavior (default):**
```yaml
mode: graph
steps:
  - name: step1
    command: echo "First"
  - name: step2
    command: echo "Second"
    depends: step1
  - name: step3
    command: echo "Third"
    depends: step2
```

**Proposed behavior:**
```yaml
mode: sequential
steps:
  - name: step1
    command: echo "First"
  - name: step2
    command: echo "Second"
  - name: step3
    command: echo "Third"
```

See [spec/SEQUENTIAL_STEP_EXECUTION.md](https://github.com/dagu-org/dagu/blob/main/spec/SEQUENTIAL_STEP_EXECUTION.md) for full specification.
